### ISSUE TITLE
youcompleteme pythonfutures suse

### ISSUE THREAD

**Issue by hurricanehrndz** [breed808/rpm-specs#2]
Just wondering why on openSUSE builds you omitted pythonfutures? Additionally, I was wondering if you would be willing to add Tumbleweed, and if you would accept a pull request to fix the builds.

Additionally,

Wondering why you never removed the gocode _testing folder.

**Comment by breed808** [comment]
The [python-futures](https://github.com/breed808/rpm-specs/blob/master/vim-youcompleteme-git/vim-youcompleteme.spec#L59) dependency is outside of the `%if %{?suse_version}` block above it, so both distros (Fedora/OpenSUSE) will add the python-futures dependency to the package.

Admittedly, I've been neglecting the OpenSUSE side of the spec file as I've been using Fedora for some time now.

The `_testing` folder is something I've missed. I'll push a fix for that shortly.

I'd be more than happy to take pull requests for Tumbleweed and/or OpenSUSE builds, as I'm not using OpenSUSE at the moment.

**Comment by hurricanehrndz** [comment]
Thank you for the feedback. I'm going to try revamp the packages specifically for openSUSE, I will let you know once I'm done and will provide a link. I believe there are a couple of issues with how it is currently built, specifically that ycmd and ycm are built from the same source yet they are now officially separate packages. Makes writing a service file for OBS to retrieve the source from git nearly impossible.

**Comment by hurricanehrndz** [comment]
Hey so, I'm now done packaging youcompleteme for openSUSE, if you wish checkout the project here:
https://build.opensuse.org/project/show/home:hurricanehernandez:youcompleteme

- ycmd and vim-youcompleteme are now separate packages
- added support for typescript and js
- enable various unit tests for both ycmd and vim-youcompleteme

One of the main reasons to have separate packages for ycmd and vim-youcompleteme is that ycmd can be used with other editors than just vim.
